import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getData } from "./home/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between p-4">
          <h1>
            Next.js
          </h1>
          <p>
            {data.name}
          </p>
          <button> Logout </button>
        </header>
        {children}</body>
    </html>
  );
}
